
include ../Makefile

NEUTRON_CODE_DIR=/wine/code/neutron

WITH_CONFIG_FILE=--config-file $(NEUTRON_CODE_DIR)/etc/neutron.conf \
			     --config-dir $(NEUTRON_CODE_DIR)/etc

cd:
	cd $(NEUTRON_CODE_DIR)	

setup:
	cd $(NEUTRON_CODE_DIR); \
	python2 ./setup.py develop

start: setup
	python2 /usr/bin/neutron-server $(WITH_CONFIG_FILE)

db-migrate:
	python2 /usr/bin/neutron-db-manage $(WITH_CONFIG_FILE) current

db-upgrade:
	python2 /usr/bin/neutron-db-manage $(WITH_CONFIG_FILE) upgrade heads

