kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
- role: control-plane
  image: kindest/node:v1.25.16
  extraMounts:
  - hostPath: /wine/devbox/opt/k8s/kind-mnt
    containerPath: /kind-mnt
  extraPortMappings:
  - containerPort: 80
    hostPort: 10080
    protocol: TCP
  - containerPort: 443
    hostPort: 10443
  - containerPort: 30001
    hostPort: 30001
  - containerPort: 30002
    hostPort: 30002
  - containerPort: 30003
    hostPort: 30003
  - containerPort: 30004
    hostPort: 30004
  - containerPort: 30005
    hostPort: 30005
  - containerPort: 30006
    hostPort: 30006
  - containerPort: 30007
    hostPort: 30007
  - containerPort: 30008
    hostPort: 30008
  - containerPort: 30009
    hostPort: 30009
- role: worker
  image: kindest/node:v1.25.16
- role: worker
  image: kindest/node:v1.25.16

