
VENV_DIR=/wine/venv

mkdir:		## mkdir venv
	mkdir -p $(VENV_DIR)

# virtualenv $(VENV_ICODE) -p python3

VENV_ICODE=$(VENV_DIR)/icode
venv-icode:
	python3.7 -m venv $(VENV_ICODE) 
	@echo
	ls $(VENV_DIR)
	pip install nicegui==1.2.24 python-socketio==5.9.0 fabric==3.2.2

