
include ../Makefile

start:
	systemctl start docker

status:
	systemctl status docker

stop:
	systemctl stop docker

restart:
	systemctl restart docker

enable:
	sudo systemctl enable --now docker.socket



