
.PHONY: build start stop run pull at attach enter exec

# env
DEVC_CENTOS_IMAGE=devc-centos-7.9:latest

ROOT_DIR=/wine
DIND_DIR=/wine/devbox/opt/dind

# help

help:
	@LC_ALL=C $(MAKE) -pRrq -f $(firstword $(MAKEFILE_LIST)) : 2>/dev/null | awk -v RS= -F: '/(^|\n)# Files(\n|$$)/,/(^|\n)# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | sort | grep -E -v -e '^[^[:alnum:]]' -e '^$@$$'

# alias 

run: start

at: enter

attach: enter

exec: enter


prune:
	docker image prune

