include ../Makefile

NEUTRON_IMAGE_FROM=devc-centos-7.9:latest
NEUTRON_IMAGE=devc-neutron:latest
NEUTRON_NAME=devc-neutron
NEUTRON_CODE_DIR=/wine/code/neutron

build: 		## docker build image 
	docker build -f ./Dockerfile \
	--build-arg IMAGE_FROM="$(NEUTRON_IMAGE_FROM)" \
	-t $(NEUTRON_IMAGE) $(NEUTRON_CODE_DIR)

start: 		## docker start container
	docker run $(DEVC_WITH_OPTIONS) \
	--name $(NEUTRON_NAME) --hostname $(NEUTRON_NAME) \
	-p 9696:9696 \
	-v $(NEUTRON_CODE_DIR):$(NEUTRON_CODE_DIR) \
	--privileged=true \
	$(NEUTRON_IMAGE)

stop:		## docker stop container
	docker stop $(NEUTRON_NAME)
	docker rm $(NEUTRON_NAME)

enter:		## attach to container
	docker exec -it $(NEUTRON_NAME) zsh


